### ISSUE TITLE
Trying to show BottomSheet inside fragment

### ISSUE THREAD

**Issue by Fuhrmann** [Commit451/ModalBottomSheetDialogFragment#2]
I'm trying to show a bottom sheet inside a custom fragment. In this fragment I implement the Listener:

```
class MyFragment : Fragment(), ModalBottomSheetDialogFragment.Listener {
}
```

Then the method:

```
override fun onModalOptionSelected(tag: String?, option: Option) {
    Snackbar.make(root, "Selected option ${option.title} from fragment with tag $tag", Snackbar.LENGTH_SHORT)
            .show()
}
``` 

Then, when I want to show the bottom sheet dialog, I just call this:

```
ModalBottomSheetDialogFragment.Builder()
    .add(R.menu.menu_options)
    .show(activity!!.supportFragmentManager, "my_bottom_sheet")
```

But just after the execution I get this error:

```
java.lang.IllegalStateException: ModalBottomSheetDialogFragment must be attached to a parent (activity or fragment) that implements the ModalBottomSheetDialogFragment.Listener
at com.commit451.modalbottomsheetdialogfragment.ModalBottomSheetDialogFragment.bindHost(ModalBottomSheetDialogFragment.kt:136)
at com.commit451.modalbottomsheetdialogfragment.ModalBottomSheetDialogFragment.onViewCreated(ModalBottomSheetDialogFragment.kt:115)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1439)
```

It is possible to show the bottom sheet dialog inside a fragment?

**Comment by Jawnnypoo** [comment]
```
ModalBottomSheetDialogFragment.Builder()
    .add(R.menu.menu_options)
    .show(childFragmentManager, "my_bottom_sheet")
```
is what you want (note the change from `activity!!.supportFragmentManager` to `childFragmentManager`

**Comment by Fuhrmann** [comment]
Yes, thank you very much! It's working now.

**Comment by Jawnnypoo** [comment]
No prob! Happy to help!

**Comment by darshi214sejpal** [comment]
@Fuhrmann can you help me with how to create bottom sheet dialog/fragment inside a fragment. I can't find any sources for it.
